### ISSUE TITLE
Weeknumbers

### ISSUE THREAD

**Issue by Rob-Post** [ng2-ui/datetime-picker#152]
It's actually more like a feature request. Is it possible to show weeknumbers in the datepicker?

**Comment by allenhwkim** [comment]
Yes, it's possible.

However, please be pecific how you want to display week numbers. 
I have my guess, but please tell me more about the following;

1.  look and feel
2. property name to control e. e.g., `show-week-number`
3. any event week numbers?
4. etc.

**Comment by Rob-Post** [comment]
Thanks.

1. I think it should look something like this:
![datepicker](https://cloud.githubusercontent.com/assets/11585297/23467393/3464d3f4-fe9e-11e6-93a2-b1562a0e275c.png)

2. I think `show-week-numbers` is a nice name 
3. I don't know and don't need any at this moment.

**Comment by allenhwkim** [comment]
Please add upvote on this feature. I am hesitant to implement this without demands from user.

**Comment by woutervandergraaf** [comment]
Would be welcome addition. Keep in mind that week numbers are different per locale. Here in NL we have other rules for week numbers than in the US.

**Comment by allenhwkim** [comment]
@woutervandergraaf thanks for your input.

**Comment by jeffreyhofstede** [comment]
This feature is very welcome! 👍
