### ISSUE TITLE
Component opens above the input

### ISSUE THREAD

**Issue by chrisbenseler** [ng2-ui/datetime-picker#174]
If the input is at the bottom of the screen:

![screenshot from 2017-03-22 08-38-39](https://cloud.githubusercontent.com/assets/1225447/24196222/b6eb4f9a-0edb-11e7-956e-e74547348df5.png)

 the datetimepicker opens above the input and the user cannot the it (the input)

![datetimepicker](https://cloud.githubusercontent.com/assets/1225447/24196202/97486240-0edb-11e7-8c64-50c7f9ad28c8.png)

**Comment by allenhwkim** [comment]
Made the dropdown draggable, so that you can change the input field.
