### ISSUE TITLE
Cannot change date or time through input element

### ISSUE THREAD

**Issue by ciesielskico** [ng2-ui/datetime-picker#182]
**Feature Request**

**Current behavior**
It is not possible to change the date or time by typing into the input. The input gets deleted.

**Expected/desired behavior**
I would like to have the choice to change the time using the keyboard or the mouse.

**Comment by allenhwkim** [comment]
Please explain more

**Comment by allenhwkim** [comment]
I got it.
Currently, input field is modifiable but whenever user enters some value, it modifies the input value to follow the date format unless the input value is blank.
I will see what I can do about it.

**Comment by skalakon** [comment]
I am still facing the issue. Is it solved?

**Comment by ciesielskico** [comment]
This is still an issue, I just installed 0.16.2 and changed the time by keyboard. I closed and reopened  the datetime-picker and it still shows old time.

**Comment by HerrSlavchev** [comment]
Same here - using 0.16.2 too. What shall we do to reopen the issue?
