### ISSUE TITLE
Design Issue Dates and Days of week are displayed wrong in calendar 

### ISSUE THREAD

**Issue by saineshwar** [ng2-ui/datetime-picker#200]
**Design Issue Dates and Days of week are displayed wrong in calendar** 

According to Calendar the  day i select it must me Tuesday but it is displaying as Friday .

![image](https://cloud.githubusercontent.com/assets/8281689/26439905/b1f9ffd8-4147-11e7-87ca-e25149ecd111.png)

The date on Windows .

![image](https://cloud.githubusercontent.com/assets/8281689/26439933/d15a05bc-4147-11e7-8457-f9fbf092d9e6.png)

**Comment by saineshwar** [comment]
Making Padding 0 0px in ng2-datetime-picker.umd.js resolved my issue

![image](https://cloud.githubusercontent.com/assets/8281689/26567436/ed862b74-4518-11e7-98c3-97f0ed8c3b89.png)

![image](https://cloud.githubusercontent.com/assets/8281689/26567452/20ebf372-4519-11e7-8d39-e691c9c3c4a5.png)

And same thing can be done in ng2-datetime-picker.component.ts Typescript file

**Comment by floouuu** [comment]
Thank you, you saved me a lot of time with your excellent answer! Have a nice day!
