### ISSUE TITLE
Year is not shown, and no change year functionality

### ISSUE THREAD

**Issue by purandharangular** [ng2-ui/datetime-picker#205]
HI i am using datetime picker in my project after following the instrucitons i am having an issue like below

![capture](https://user-images.githubusercontent.com/29742534/27615735-790254c4-5bfe-11e7-99ef-1cdcb5ba61bf.PNG)

pleae help

**Comment by purandharangular** [comment]
it is not showing the year and month label and when i click multiple times on the blank area where it is supposed to display year an dmonth , years will be dislayed and wont be visible except on mouse hover.

**Comment by allenhwkim** [comment]
I have never seen this issue. Can you create a plunker example?

**Comment by purandharangular** [comment]
no isues it is CSS issue. sorted out. thanks
